### ISSUE TITLE
HR Branding Campaign Plan

### ISSUE THREAD

**Issue by asyaisakova** [inca-digital/challenge#66]
Imagine you need to lead a 3-month $5000 HR Branding Campaign. Using the information below, try creating and prioritizing specific campaign do-outs. What would the roadmap look like? What would you do yourself? How would you leverage other people and services?

**Goal of the campaign**: increase the flow of highly-motivated candidates though promoting our lifestyle and core values.

**Target audience**: potential candidates researching our company, looking for challenging remote jobs, and generally interested in nomad lifestyle.

**Platforms**: Instagram, LinkedIn, Twitter, and YouTube.

**Resources**: [Employee interviews](https://drive.google.com/drive/folders/1Mxg8Ph22tuSv6p2urURl1mbNmGyFQ2Za?usp=sharing), [Careers page](https://inca.digital/careers/), [Intelligence portal](https://inca.digital/intelligence/), and [Handbook](https://inca.digital/handbook/welcome-to-our-team).

Don't hesitate to ask us questions by commenting in this issue or emailing us at challenge@inca.digital.

**Comment by ebsi99** [comment]
Hi! I created a plan to grow your business on social media. You can see the general outline in the following google slides link.

https://docs.google.com/presentation/d/1RFkDoIJcxjrFExVKkiC-twLQ-AETgmohQBDsP_AQFmE/edit?usp=sharing

**Comment by ToriAlikhanova** [comment]
Hello there! I was wondering if Social Media Plan challenge is still relevant, or was it changed to HR Branding Campaign? Which one has to be submitted for the Social Media Content Specialist Position? Thanks!

**Comment by evgenydmitriev** [comment]
Either would work. We changed it because we didn't get enough quality submissions.

**Comment by Peculidar** [comment]
Hi!

I am applying for the role of **Social Media Content Specialist**. I do not have a fancy PowerPoint presentation, but I can give a brief overview of the roadmap I would propose for such a campaign as well as the actions I would take as a social media content strategist:

**Step 1**
Separate HR branding strategies from sales team strategies. Right now the Inca.Digital website attempts to do too much by appealing both to clients and potential employees. I believe this is a mistake, because employees care about freedom and work-life balance, whereas fintech clients care about precision, reliability, and turnover rates. 

**Step 2**
For the HR campaign, I would recommend hiring a branding team with strong visual communication skills that will incorporate the company spirit of freedom and love of the nomadic lifestyle. They would undertake such actions as logo improvement, color palette correction, typography choice, and more.

**Step 3** _(this is what I personally would do as a **Social Media Content Specialist**)_
Incorporate assets created by the branding specialists across all platforms. Specifically:
- Create visual content plan for Instagram which includes Reels & Stories content that will appeal to IT specialists
- Develop a witty, informational content plan for Twitter that includes opportunities for engagement with industry specialists (through smart hastag use)
- Combine visuals with informational content for the Facebook content plan
- Use employee interviews and branding assets in creating a dynamic and engaging Youtube content plan

**Step 4**
Use remains of budget to promote posts across all platforms.

In my experience, this is the smartest approach. Also, the above is just a brief overview, obviously developing an actual campaign takes a lot of time, effort, and input from specialists across different departments.

Thank you for reading 🙂

**Comment by platonaska** [comment]
Hello, it seems a 3-month 5000$ HR Branding campaign is in process already. 
Step 1: Register your company on hh.ru, pay for the service.
Step 2: Upload an appealing job description with a desirable salary and work conditions.
Step 3: Give a challenge to filter unqualified candidates out and set a meeting with active ones who were ready to spend their time on that challenge, therefore are interested in a job offer. 
... 
If you are in the particular business for quite a long time, you would probably know a lot of well-qualified specialists, most likely in person, so you could try to headhunt them by offering better work conditions, salary or whatever they lack of at the recent company they work for. Surely, LinkedIn can be used for the same purpose.

**Comment by Mahmoud1115** [comment]
https://hh.ru/resume/4eb3176fff080d82100039ed1f38714f326861

**Comment by polinashirykalova** [comment]
Hi!

I would like to apply for SM Content Specialist Position. 
The task was fun, thank you!

Please find my Campaign Plan attached. 
[HR Branding Campaign.pdf](https://github.com/inca-digital/challenge/files/7877100/HR.Branding.Campaign.pdf)

Regards,
Polina Shirykalova

shirykalova.pa@icloud.com
