### ISSUE TITLE
Fix Instagram account

### ISSUE THREAD

**Issue by evgenydmitriev** [inca-digital/challenge#72]
Name 1 thing apart from visual style that you would change first about [our Instagram](https://www.instagram.com/inca.digital/) and write better captions for 5 of our posts. Please email careers@inca.digital with your ideas, and don't forget to attach your resume.

**Comment by christina-do** [comment]
Done! My submission is forwarded to the given address

**Comment by Yuliachudi** [comment]
I completed the task, emailed the link and my CV! Thanks!

**Comment by Khalil-Sh** [comment]
Sent an email.

**Comment by polinaspirit** [comment]
Hello! 

First of all, I  would prioritize video content and stories rather than posts with long captions
IG Reels promotes your Reels organically, and you also can use the same content in Tik Tok and YouTube shorts. And guess what? They also promote your content organically =) This is a rare opportunity, don't miss it!

Since you specialize in fintech I would suggest a series of short videos devoted to bitcoin and remote style of work.
Make them funny and you will see viral growth for sure!

You asked for five captions, but since I am already talking about video, I will suggest 5 reels instead: 

1) Viral sound "Can we skip to the good part - no" 
https://www.instagram.com/reel/Ccy5s2qpYA6/?igshid=YmMyMTA2M2Y=

Showing diagrams of bitcoin (any other coin) growing, then falling. Use MacBook in the frame, pretty scenery, and a hand with the cocktail shaking terribly. 

2) Viral trend "Paris called and I answered"
https://www.instagram.com/reel/CcXvAZ4KfD4/?igshid=YmMyMTA2M2Y=
Promote remote style work. Telephone with "Inca.Digital" and then show all the beautiful places around the world your team works at. 

3) Working at the office VS Working at home. What will you choose? 

Trending sound: https://www.instagram.com/reel/CcV2J5-oTEN/?igshid=YmMyMTA2M2Y=

Show working in cozy bedroom and then in trendy office space. Ask subscribers what would they choose.

4) All the nice places we went for workation: 
https://www.instagram.com/reel/CcV2J5-oTEN/?igshid=YmMyMTA2M2Y=
Use this sound and the best pictures you made abroad.

5) People working in most unexpected places compilation
Trending sound: https://www.instagram.com/reel/CdAt3sqIVt0/?igshid=YmMyMTA2M2Y=

Show team working from the beach, at home, in the office, coffee shop, farm, fishing market etc. 

I also recommend checking TikTok account @briskly_house for inspiration!

Best, Polina
WA +79147026028

**Comment by VoskresenskiyDenis** [comment]
Hello!

I emailed you the completed challenge and my CV.
Thank you!

Best regards, 
Denis Voskresenskiy

WA +33652680738
Telegram and phone +79869520744
E-mail: d.voskresenskiy@hotmail.com
